# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-14 00:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_proof_blanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer_keys',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='feedback_keys',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint_keys',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=None, null=True),
        ),
    ]
