# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems_proof_blanks', '0003_auto_20200715_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems_proof_blanks.Problem'),
        ),
    ]
