# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionquestposition',
            name='content_sectionquest',
        ),
        migrations.DeleteModel(
            name='SectionQuestPosition',
        ),
    ]
