# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_SectionQuestPosition'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedvideo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='watchedvideo',
            unique_together=set([]),
        ),
    ]
