# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_video_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionquestposition',
            name='content_sectionquest',
        ),
        migrations.DeleteModel(
            name='SectionQuestPosition',
        ),
    ]
