# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170606_1400'),
        ('content', '0003_add_video_timestamp'),
    ]

    operations = [
    ]
