# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCRSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='username')),
                ('code_style', models.CharField(choices=[('monokai', 'Dark Background'), ('eclipse', 'Light Background'), ('shaped', 'Black and White')], default='monokai', max_length=7)),
                ('use_simpleui', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_ta', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.SlugField(max_length=10, primary_key=True, serialize=False, verbose_name='section id')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='section description')),
                ('location', models.CharField(max_length=10, verbose_name='location')),
                ('lecture_time', models.CharField(max_length=20, verbose_name='lecture time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pcrsuser',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Section'),
        ),
    ]
