# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_fa_visuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='max_chars',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='min_chars',
        ),
        migrations.AddField(
            model_name='problem',
            name='regex',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
