# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-30 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_fa_visuals', '0002_auto_20200629_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='keys',
        ),
    ]
