# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('content', '0007_auto_20171027_1416'),
        ('problems_parsons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='problem',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_parsons_problem_related', to='content.Challenge'),
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='max_score',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems_parsons_problem_related', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='problem',
            name='visibility',
            field=models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='has_best_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_parsons_submission_related', to='users.Section'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='invariant',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='unit_tests',
            field=models.TextField(blank=True),
        ),
    ]
