# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-25 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_parsons', '0002_auto_20200620_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
