# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-15 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems_parsons', '0003_auto_20200625_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Testcase visible to students')),
                ('description', models.TextField(blank=True)),
                ('pre_code', models.TextField(blank=True, default='')),
                ('test_input', models.TextField()),
                ('expected_output', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='evaluation_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Evaluate using all methods'), (1, 'Evaluate using line comparison (simple)'), (2, 'Evaluate using unit tests method')], max_length=1),
        ),
        migrations.AddField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_parsons.Problem'),
        ),
    ]
