# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-08 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_parsons', '0006_testrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='max_score',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
