# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-13 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_parsons', '0008_auto_20200807_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='max_score',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
