# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=30)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=30, unique=True)),
                ('definition', models.TextField()),
                ('representation', models.TextField()),
                ('tables', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_rdb.Schema'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('name', 'schema')]),
        ),
    ]
