# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11 on 2017-07-06 21:25
=======
# Generated by Django 1.11 on 2017-06-06 18:00
>>>>>>> dfdc824d77bb2ebd36d6474cb72458070e3ecf2d
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_short_answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='max_chars',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
