# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 20:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_short_answer', '0004_hstore_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.AddField(
            model_name='problem',
            name='keys',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=None),
        ),
    ]
