# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_short_answer', '0005_auto_20170802_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='min_chars',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
