# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems_r', '0002_submission_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.FileUpload'),
        ),
    ]
