# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_r', '0003_auto_20170606_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='dataset',
        ),
        migrations.AddField(
            model_name='submission',
            name='file_upload',
            field=models.CharField(default='', max_length=100),
        ),
    ]
