# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20170607_1322'),
        ('problems_r', '0004_auto_20170607_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='submission',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.FileUpload'),
        ),
    ]
