# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20170609_0832'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems_r', '0005_auto_20170607_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSubmissionManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.FileUpload')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_r.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
