# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_r', '0006_filesubmissionmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='allow_data_set',
            field=models.BooleanField(default=True),
        ),
    ]
