# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20170612_1116'),
        ('problems_r', '0007_problem_allow_data_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='dataset',
        ),
        migrations.AddField(
            model_name='problem',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.FileUpload'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='passed',
            field=models.BooleanField(default=True),
        ),
    ]
