# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_r', '0008_auto_20170612_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='dataset',
            new_name='data_set',
        ),
    ]
