# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_r', '0009_auto_20170612_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='testcase',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
    ]
