# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('problems', '0001_initial'), ('problems', '0002_auto_20170606_1658'), ('problems', '0003_auto_20170607_1010'), ('problems', '0004_auto_20170607_1237'), ('problems', '0005_auto_20170607_1321'), ('problems', '0006_auto_20170607_1322'), ('problems', '0007_auto_20170608_2020'), ('problems', '0008_auto_20170608_2021'), ('problems', '0009_auto_20170608_2025'), ('problems', '0010_auto_20170608_2145'), ('problems', '0011_auto_20170609_0832'), ('problems', '0012_auto_20170609_1650'), ('problems', '0013_auto_20170612_1116'), ('problems', '0014_auto_20170612_1216'), ('problems', '0015_auto_20170612_1442'), ('problems', '0016_auto_20170612_1443'), ('problems', '0017_auto_20170612_1449'), ('problems', '0018_auto_20170612_1452'), ('problems', '0019_auto_20170612_1455'), ('problems', '0020_auto_20170616_0949'), ('problems', '0021_auto_20170619_1018'), ('problems', '0022_auto_20170619_1143'), ('problems', '0023_auto_20170619_1613'), ('problems', '0024_auto_20170620_1036'), ('problems', '0025_auto_20170719_1036'), ('problems', '0026_auto_20170719_1051'), ('problems', '0027_auto_20170719_1054'), ('problems', '0028_auto_20170719_1102'), ('problems', '0029_auto_20170719_1105'), ('problems', '0030_auto_20170719_1106'), ('problems', '0031_auto_20170719_1111'), ('problems', '0032_auto_20170719_1121'), ('problems', '0033_auto_20170719_1124'), ('problems', '0034_auto_20170720_1040'), ('problems', '0035_auto_20170720_1045'), ('problems', '0036_auto_20170720_1051'), ('problems', '0037_auto_20170720_1051')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('lifespan', models.DateTimeField(default=datetime.datetime(2017, 7, 21, 14, 51, 45, 184337, tzinfo=utc), null=True)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
