# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('lifespan', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 52, 17, 789029))),
            ],
        ),
    ]
