# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('lifespan', models.DateTimeField(default=datetime.datetime(2017, 8, 26, 16, 7, 4, 524378, tzinfo=utc), null=True)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
