# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 6, 18, 42, 202844, tzinfo=utc), null=True),
        ),
    ]
