# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170828_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 2, 26, 19, 772473, tzinfo=utc), null=True),
        ),
    ]
