# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20170607_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 12, 37, 21, 296618)),
        ),
    ]
