# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20171027_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 21, 24, 0, 998377, tzinfo=utc), null=True),
        ),
    ]
