# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-15 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20200607_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 22, 59, 43, 687951, tzinfo=utc), null=True),
        ),
    ]
