# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-29 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20200629_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 20, 58, 57, 438523, tzinfo=utc), null=True),
        ),
    ]
