# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20170607_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 13, 21, 37, 93679)),
        ),
    ]
