# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-27 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20200615_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 22, 49, 35, 971081, tzinfo=utc), null=True),
        ),
    ]
