# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-27 23:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20200627_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 23, 43, 12, 175788, tzinfo=utc), null=True),
        ),
    ]
