# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 00:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20170607_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 20, 20, 11, 10023), null=True),
        ),
    ]
