# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-25 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_auto_20200620_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 22, 8, 31, 256141, tzinfo=utc), null=True),
        ),
    ]
