# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20170608_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 0, 25, 49, 697966, tzinfo=utc), null=True),
        ),
    ]
