# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-03 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20200625_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 22, 57, 7, 910494, tzinfo=utc), null=True),
        ),
    ]
