# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-13 03:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20200625_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 3, 54, 48, 426363, tzinfo=utc), null=True),
        ),
    ]
