# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-21 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20200715_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 11, 59, 25, 387082, tzinfo=utc), null=True),
        ),
    ]
