# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-22 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20200722_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 15, 17, 52, 259342, tzinfo=utc), null=True),
        ),
    ]
