# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-15 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20200714_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 2, 40, 48, 335306, tzinfo=utc), null=True),
        ),
    ]
