# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20170609_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 20, 50, 14, 222248, tzinfo=utc), null=True),
        ),
    ]
