# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20170609_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 15, 16, 31, 121499, tzinfo=utc), null=True),
        ),
    ]
