# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20170612_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 16, 16, 19, 814878, tzinfo=utc), null=True),
        ),
    ]
