# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-22 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20200722_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 19, 36, 37, 96973, tzinfo=utc), null=True),
        ),
    ]
