# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-16 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_auto_20200722_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 21, 41, 2, 226730, tzinfo=utc), null=True),
        ),
    ]
