# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_auto_20170612_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='name',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 18, 43, 43, 571583, tzinfo=utc), null=True),
        ),
    ]
