# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-08 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_auto_20200807_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 3, 14, 48, 755714, tzinfo=utc), null=True),
        ),
    ]
