# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_auto_20170612_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 13, 49, 20, 351670, tzinfo=utc), null=True),
        ),
    ]
