# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_auto_20170616_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 14, 18, 7, 269010, tzinfo=utc), null=True),
        ),
    ]
