# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_auto_20170619_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 20, 13, 57, 960954, tzinfo=utc), null=True),
        ),
    ]
