# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_auto_20170619_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 14, 36, 1, 275018, tzinfo=utc), null=True),
        ),
    ]
