# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0024_auto_20170620_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 14, 36, 2, 630813, tzinfo=utc), null=True),
        ),
    ]
