# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_python', '0002_problem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='pre_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
