# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import problems.models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_python', '0003_testcase_pre_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyTAClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, problems.models.SubmissionPreprocessorMixin),
        ),
        migrations.AddField(
            model_name='submission',
            name='pyta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pytaclickevent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_python.Submission'),
        ),
    ]
